version: '2.13.0'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: agustin
      POSTGRES_DB: postgres
  app:
    image: 'challenge:latest'
    build:
      context: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=agustin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080